#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 06 11:19:19 CEST 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ngen_tb_behav -key {Behavioral:sim_1:Functional:ngen_tb} -tclbatch ngen_tb.tcl -log simulate.log"
xsim ngen_tb_behav -key {Behavioral:sim_1:Functional:ngen_tb} -tclbatch ngen_tb.tcl -log simulate.log

